CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_LOG_LEVEL_DBG=y

CONFIG_GPIO=y

# Enable FPU on Cortex-M with single-precision (typical M4F/M33F)
CONFIG_FPU=y
CONFIG_FPU_SHARING=y        # if multiple threads/ISRs use floats

# Make IRQ stack bigger (primary fix for “Fault during interrupt handling”)
   # try 2048 or 3072 on nRF54L15

# Give the system workqueue more room (our handler runs here)
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_ISR_STACK_SIZE=3072
